# -*- coding: utf-8 -*-
"""“欢迎使用 Colaboratory”的副本

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12X1SstOYNZOsMT9b5IdKII7OnttEtVao

<h1>什么是 Colab？</h1>

借助 Colaboratory（简称 Colab），您可在浏览器中编写和执行 Python 代码，并且： 
- 无需任何配置
- 免费使用 GPU
- 轻松共享

无论您是一名<strong>学生</strong>、<strong>数据科学家</strong>还是 <strong>AI 研究员</strong>，Colab 都能够帮助您更轻松地完成工作。您可以观看 <a href="https://www.youtube.com/watch?v=inN8seMm7UI">Colab 简介</a>了解详情，或查看下面的入门指南！

## <strong>使用入门</strong>

您正在阅读的文档并非静态网页，而是一个允许您编写和执行代码的交互式环境，称为 <strong>Colab 笔记本</strong>。

例如，以下<strong>代码单元格</strong>包含一个简短的 Python 脚本，该脚本会计算值、将其存储在变量中并输出结果：
"""

from google.colab import drive
drive.mount('/content/gdrive')

seconds_in_a_day = 24 * 60 * 60
seconds_in_a_day

"""要执行上述单元格中的代码，请点击选择它，然后按代码左侧的“播放”按钮，或使用键盘快捷键“Command/Ctrl+Enter”。要修改代码，只需点击单元格，然后开始修改。

您在某个单元格中定义的变量之后可用在其他单元格中：
"""

seconds_in_a_week = 7 * seconds_in_a_day
seconds_in_a_week

"""对于 Colab 笔记本，您可以将<strong>可执行代码</strong>、<strong>富文本</strong>以及<strong>图像</strong>、<strong>HTML</strong>、<strong>LaTeX</strong> 等内容合入 1 个文档中。当您创建自己的 Colab 笔记本时，系统会将这些笔记本存储在您的 Google 云端硬盘帐号名下。您可以轻松地将 Colab 笔记本共享给同事或好友，允许他们评论甚至修改笔记本。要了解详情，请参阅 <a href="/notebooks/basic_features_overview.ipynb">Colab 概览</a>。要创建新的 Colab 笔记本，您可以使用上方的“文件”菜单，也可以使用以下链接：<a href="http://colab.research.google.com#create=true">创建新的 Colab 笔记本</a>。

Colab 笔记本是由 Colab 托管的 Jupyter 笔记本。如需详细了解 Jupyter 项目，请访问 <a href="https://www.jupyter.org">jupyter.org</a>。

## 数据科学

借助 Colab，您可以充分利用常用 Python 库的强大功能来分析和可视化数据。下方的代码单元格使用 <strong>NumPy</strong> 生成一些随机数据，并使用 <strong>Matplotlib</strong> 可视化这些数据。要修改代码，只需点击单元格，然后开始修改。
"""

import numpy as np
from matplotlib import pyplot as plt

ys = 200 + np.random.randn(100)
x = [x for x in range(len(ys))]

plt.plot(x, ys, '-')
plt.fill_between(x, ys, 195, where=(ys > 195), facecolor='g', alpha=0.6)

plt.title("Sample Visualization")
plt.show()

"""您可将自己的数据导入 Colab 笔记本中，支持的数据来源有：Google 云端硬盘帐号（包括电子表格）、GitHub 以及其他很多来源。要详细了解如何导入数据及将 Colab 用于数据科学领域，请访问下方<a href="#working-with-data">处理数据</a>下的链接。

## 机器学习

借助 Colab，您只需使用<a href="https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/quickstart/beginner.ipynb">几行代码</a>，即可导入图像数据集、用图像数据集训练图像分类器，以及评估模型。Colab 笔记本会在 Google 的云服务器中执行代码，也就是说，无论您所用机器的功能如何，您都可以利用 Google 硬件（包括 <a href="#using-accelerated-hardware">GPU 和 TPU</a>）的强大性能。只要有个浏览器即可。

Colab 在机器学习社区内得到了广泛应用，应用示例包括：
- TensorFlow 使用入门
- 开发和训练神经网络
- 使用 TPU 进行实验
- 推广 AI 研究
- 创建教程

要查看演示机器学习应用的示例 Colab 笔记本，请查看下方的<a href="#machine-learning-examples">机器学习示例</a>。

## 更多资源

### 在 Colab 中使用笔记本
- [Colaboratory 概览](/notebooks/basic_features_overview.ipynb)
- [Markdown 指南](/notebooks/markdown_guide.ipynb)
- [导入库和安装依赖项](/notebooks/snippets/importing_libraries.ipynb)
- [在 GitHub 中保存和加载笔记本](https://colab.research.google.com/github/googlecolab/colabtools/blob/main/notebooks/colab-github-demo.ipynb)
- [互动表单](/notebooks/forms.ipynb)
- [互动微件](/notebooks/widgets.ipynb)
- <img src="/img/new.png" height="20px" align="left" hspace="4px" alt="New"></img>
 [在 Colab 中使用 TensorFlow 2](/notebooks/tensorflow_version.ipynb)

<a name="working-with-data"></a>
### 处理数据
- [加载数据：云端硬盘、表格和 Google Cloud Storage](/notebooks/io.ipynb) 
- [图表：可视化数据](/notebooks/charts.ipynb)
- [BigQuery 使用入门](/notebooks/bigquery.ipynb)

### 机器学习速成课程
以下是 Google 在线机器学习课程中的部分笔记本。请查看<a href="https://developers.google.com/machine-learning/crash-course/">完整课程网站</a>了解详情。
- [Pandas DataFrame 简介](https://colab.research.google.com/github/google/eng-edu/blob/main/ml/cc/exercises/pandas_dataframe_ultraquick_tutorial.ipynb)
- [通过 tf.keras 使用合成数据进行线性回归](https://colab.research.google.com/github/google/eng-edu/blob/main/ml/cc/exercises/linear_regression_with_synthetic_data.ipynb)


<a name="using-accelerated-hardware"></a>
### 使用加速硬件
- [将 TensorFlow 与 GPU 配合使用](/notebooks/gpu.ipynb)
- [将 TensorFlow 与 TPU 配合使用](/notebooks/tpu.ipynb)

<a name="machine-learning-examples"></a>

### 精选示例

- <a href="https://colab.research.google.com/github/NVIDIA/NeMo/blob/stable/tutorials/VoiceSwapSample.ipynb">NeMo Voice Swap</a>：借助 Nvidia 的 NeMo 会话式 AI 工具包，您可以将音频片段中的语音换成计算机生成的语音。

- <a href="https://tensorflow.org/hub/tutorials/tf2_image_retraining">重新训练图像分类器</a>：基于预训练的图像分类器，构建一个分辨花朵的 Keras 模型。
- <a href="https://tensorflow.org/hub/tutorials/tf2_text_classification">文本分类</a>：将 IMDB 影评分类为“褒义”<em></em>或<em></em>“贬义”。
- <a href="https://tensorflow.org/hub/tutorials/tf2_arbitrary_image_stylization">风格迁移</a>：使用深度学习在图像之间迁移风格。
- <a href="https://tensorflow.org/hub/tutorials/retrieval_with_tf_hub_universal_encoder_qa">Multilingual Universal Sentence Encoder Q&amp;A</a>：使用机器学习模型回答来自 SQuAD 数据集中的问题。
- <a href="https://tensorflow.org/hub/tutorials/tweening_conv3d">视频插帧</a>：预测视频第一帧和最后一帧之间有些什么。
"""

import pandas as pd
import numpy as np
import jieba
import json
import codecs
import os
import yaml
from gensim.models.word2vec import Word2Vec
from gensim.corpora.dictionary import Dictionary
from tensorflow.keras.preprocessing import sequence
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from keras.layers import *
from tensorflow.keras.models import model_from_yaml
from tensorflow.keras.callbacks import ReduceLROnPlateau
import multiprocessing
import matplotlib.pyplot as plt
from config import Config

print(Config.word_path)
print(Config.w2indx_path)
print(Config.w2vec_path)
print(Config.combined_path)

vocab_dim = 200  # 词向量维度
maxlen = 100     # 序列最大长度
n_iterations = 10  # 迭代次数
n_exposures = 10    # 词频截断值
window_size = 7  # 窗口大小
batch_size = 1024  # 批次大小
n_epoch = 30      # 迭代次数
input_length = 100  # 输入序列长度
cpu_count = multiprocessing.cpu_count()  #

def load_file():
    """加载数据"""
    # 加载数据集
    null = pd.read_csv(Config.new_List[0], header=None, index_col=None)  # null
    like = pd.read_csv(Config.new_List[1], header=None, index_col=None)  # like
    sad = pd.read_csv(Config.new_List[2], header=None, index_col=None)  # sad
    disgust = pd.read_csv(Config.new_List[3], header=None, index_col=None)  # disgust
    anger = pd.read_csv(Config.new_List[4], header=None, index_col=None)  # anger
    happy = pd.read_csv(Config.new_List[5], header=None, index_col=None)  # happy

    # concatenate 能够一次完成多个数组的拼接
    combined = np.concatenate((null[0], like[0], sad[0], disgust[0], anger[0], happy[0]))
    print(type(combined))
    # null-0 like-1 sad-2 disgust-3 anger-4 happy-5
    y = np.concatenate((np.zeros(len(null), dtype=int), np.ones(len(like), dtype=int),
                        np.ones(len(sad), dtype=int) * 2, np.ones(len(disgust), dtype=int) * 3,
                        np.ones(len(anger), dtype=int) * 4, np.ones(len(happy), dtype=int) * 5))

    return combined, y

def tokenizer(text):
    """对句子经行分词，并去掉换行符，结果保存再word.json文件中"""
    print("开始分词")
    word_json = codecs.open(Config.word_path, 'w', encoding=Config.encoding)
    stopwords = codecs.open(Config.stop_words_path, encoding='utf-8', errors='replace')  # 加载停用词
    stop_words, text = [], []
    for line in stopwords:
        stop_words.append(line.strip())

    for document in combined:
        word_list = jieba.lcut(document.replace('\n', ''))
        for w in word_list:
            if w in stop_words:
                word_list.remove(w)
        text.append(word_list)

    json.dump(text, word_json)

    word_json.close()
    return text

def create_dictionaries(model=None, combined=None):
    """创建词语字典，并返回每个词语的索引，词向量，以及每个句子所对应的词语索引"""
    if (combined is not None) and (model is not None):
        if os.path.exists(Config.word_path) and os.path.exists(Config.w2vec_path) and os.path.exists(Config.w2indx_path):    # 已写入
            print("加载词典")
            w2indx_json = codecs.open(Config.w2indx_path, 'r', encoding=Config.encoding)
            w2vec_json = codecs.open(Config.w2vec_path, 'r', encoding=Config.encoding)
            combined_json = codecs.open(Config.combined_path, 'r', encoding=Config.encoding)

            w2indx = json.load(w2indx_json)
            W2VEC = json.load(w2vec_json)   # 加载的数组为list，需转换为numppy数组
            combined = np.loadtxt(combined_json)

            # 转换
            w2vec =dict()
            for key, value in W2VEC.items():
                w2vec[key] = np.asarray(value)

            w2indx_json.close()
            w2vec_json.close()
            combined_json.close()

            return w2indx, w2vec, combined
        else:
            gensim_dict = Dictionary()  # 创建一个空的词典,构建 word<->id 映射
            gensim_dict.doc2bow(list(model.wv.index_to_key),
                                allow_update=True)  # 构建词袋，每个单词对应一个id，词袋中的单词不重复
            w2indx = {v: k + 1 for k, v in gensim_dict.items()}  # 所有频数超过10的词语的索引字典
            w2vec = {word: model.wv[word] for word in w2indx.keys()}  # 所有频数超过10的词语的词向量字典
            W2VEC = {word: model.wv[word].tolist() for word in w2indx.keys()} # 将numpy数组转换为list存储
            def parse_dataset(combined):
                """将combined中的数据转换为索引表示"""
                data = []
                for sentence in combined:
                    new_txt = []
                    for word in sentence:
                        try:
                            new_txt.append(w2indx[word])
                        except:
                            new_txt.append(0)
                    data.append(new_txt)
                return data

            combined = parse_dataset(combined)  # 将combined中的数据转换为索引表示
            combined = sequence.pad_sequences(combined, maxlen=maxlen)  # 每个句子所含词语对应的索引，所以句子中含有频数小于10的词语，索引为0

            w2indx_json = codecs.open(Config.w2indx_path, 'w', encoding=Config.encoding)
            w2vec_json = codecs.open(Config.w2vec_path, 'w', encoding=Config.encoding)
            combined_json = codecs.open(Config.combined_path, 'w', encoding=Config.encoding)

            json.dump(w2indx, w2indx_json)
            json.dump(W2VEC, w2vec_json)
            np.savetxt(combined_json, combined) # numpy.ndarrayi

            w2indx_json.close()
            w2vec_json.close()
            combined_json.close()

            return w2indx, w2vec, combined
    else:
        print('No data provided...')

def word2vec_train(combined):
    """创建词语字典，并返回每个词语的索引，词向量，以及每个句子所对应的词语索引"""
    # size：是指特征向量的维度  min_count:对字典做截断. 词频少于min_count次数的单词会被丢弃掉
    # window：表示当前词与预测词在一个句子中的最大距离是多少  workers：参数控制训练的并行数。
    # iter： 迭代次数，默认为5
    model = Word2Vec( vector_size=vocab_dim,min_count=n_exposures,window=window_size,workers=cpu_count,epochs=n_iterations)

    model.build_vocab(combined)     # 准备模型向量
    model.train(combined,total_examples=model.corpus_count,epochs=model.epochs)   # 训练词向量
    model.save('Data/Word2vec_model.pkl')  # 保存
    index_dict, word_vectors, combined = create_dictionaries(model=model, combined=combined)
    return index_dict, word_vectors, combined

def get_data(index_dict, word_vectors, combined, y):
    n_symbols = len(index_dict) + 1  # 所有单词的索引数，频数小于10的词语索引为0，所以加1
    embedding_weights = np.zeros((n_symbols, vocab_dim))    # 索引为0的词语，词向量全为0
    for word, index in index_dict.items():  # 从索引为1的词语开始，对每个词语对应其词向量
        embedding_weights[index, :] = word_vectors[word]
    x_train, x_test, y_train, y_test = train_test_split(combined, y, test_size=0.2)

    print(x_train.shape,y_train.shape)

    return n_symbols,embedding_weights,x_train,y_train,x_test,y_test

##定义网络结构
def train_lstm(n_symbols,embedding_weights,x_train,y_train,x_test,y_test):
    print('Defining a Simple tensorflow.keras Model...')
    model = Sequential()  # or Graph or whatever
    model.add(Embedding(output_dim=vocab_dim,
                        input_dim=n_symbols,
                        mask_zero=True,
                        weights=[embedding_weights],
                        input_length=input_length))  # Adding Input Length
    model.add(LSTM(units=50, activation='tanh'))
    model.add(Activation('hard_sigmoid'))
    model.add(Dropout(0.5))
    model.add(Dense(6, activation='softmax')) # Dense=>全连接层,输出维度=6
    model.add(Activation('softmax'))

    print('Compiling the Model...')
    reduce_lr = ReduceLROnPlateau(monitor='val_loss', patience=5, mode='auto')
    
    model.compile(loss='sparse_categorical_crossentropy',
                  optimizer='adam', metrics=['accuracy'])
    model.summary()

    print("Train...") # batch_size=128
    
    history = model.fit(x_train, y_train,
                        batch_size=batch_size, epochs=n_epoch,
                        validation_split=0.1, callbacks=[reduce_lr],
                        verbose=1, validation_data=(x_test, y_test))
    print(model.eopchs)
    print(model.batch_sizz)
    
    acc = history.history['accuracy']
    loss = history.history['loss']
    epochs = range(1, len(acc) + 1)

    plt.title('Accuracy and Loss')
    plt.plot(epochs, acc, 'red', label='Training acc')
    plt.plot(epochs, loss, 'blue', label='Validation loss')
    plt.legend()
    plt.show()

    print("Evaluate...")
    score = model.evaluate(x_test, y_test, batch_size=batch_size)

    yaml_string = model.to_yaml()
    with open('model/lstm.yml', 'w') as outfile:
        outfile.write(yaml.dump(yaml_string, default_flow_style=True) )
    model.save_weights('model/lstm.h5')
    print('Test score:', score)

#训练模型，并保存
print('Loading Data...')
combined,y =load_file()
print(len(combined), len(y))

print('Tokenising...')
if os.path.exists(Config.word_path):
    print("文件已存在")
    word_json = codecs.open(Config.word_path, encoding=Config.encoding, errors='replace')
    combined = json.load(word_json)
    word_json.close()
else:
    combined = tokenizer(combined)
print('Training a Word2vec model...')
index_dict, word_vectors, combined = word2vec_train(combined)
print(type(index_dict),type(word_vectors),type(combined))

print('Setting up Arrays for tensorflow.keras Embedding Layer...')
n_symbols, embedding_weights, x_train, y_train, x_test, y_test = get_data(index_dict, word_vectors, combined, y)

print("x_train.shape and y_train.shape:")
print(x_train.shape, y_train.shape)
train_lstm(n_symbols, embedding_weights, x_train, y_train, x_test, y_test)

